name: Deploy to EC2

on:
  push:
    branches:
      - master


jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Create .env File
        run: |
          touch .env
          echo "HOSTNAME=${{ secrets.HOSTNAME }}" >> .env
          echo "WEATHER_DATABASE=${{ secrets.WEATHER_DATABASE }}" >> .env
          echo "USERNAME=${{ secrets.DB_USERNAME }}" >> .env
          echo "PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "PORT=${{ secrets.DB_PORT }}" >> .env
          echo "API_KEY=${{ secrets.OPENWEATHER_API_KEY }}" >> .env

      - name: Create Deployment Archive
        run: |
          zip -r app_deployment.zip .

      - name: Transfer Code to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_IP_ADDRESS }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: app_deployment.zip
          target: /home/ubuntu/

      - name: Deploy and Setup Application
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_IP_ADDRESS }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
         
            mkdir -p /home/ubuntu/app
            cd /home/ubuntu/
            
          
            rm -rf ./*
            
         
            unzip -o ~/app_deployment.zip
            
         
            rm ~/app_deployment.zip
            
         
            python3 -m venv venv
            source venv/bin/activate
            
            
            pip install -r requirements.txt
            pip install gunicorn
            
          
            sudo tee /etc/systemd/system/flask-app.service > /dev/null <<EOF
            [Unit]
            Description=Gunicorn Flask Application
            After=network.target

            [Service]
            User=ubuntu
            Group=ubuntu
            WorkingDirectory=/home/ubuntu/app
            ExecStart=/home/ubuntu/venv/bin/gunicorn \
                --workers 3 \
                --bind 0.0.0.0:5000 \
                --access-logfile - \
                --error-logfile - \
                app:app

            [Install]
            WantedBy=multi-user.target
            EOF
            
        
            sudo systemctl daemon-reload
            sudo systemctl enable flask-app
            sudo systemctl restart flask-app
            
           
            sudo systemctl status flask-app

      - name: Cleanup Local Zip
        run: rm app_deployment.zip

